export type ImageType = 'image/png' | 'image/jpeg' | 'image/jpg' | 'image/webp' | 'image/gif'

export type AspectRatio =
    | 'custom'
    | 'custom_circle'
    | 'square'
    | 'circle'
    | 'portrait'
    | 'landscape'
    | 'horizontal'
    | 'vertical'
    | 'grid'
    | 'board'
    | 'header'
    | 'pint'
    | 'cover'
